config/routes.rb
Baseapp::Application.routes.draw do

  # The front end site
  
  get "pages/index"
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'password', :confirmation => 'confirmation' }
  
  # When we log in a user through Devise, redirect them to the dashboard
  
  match '/user', :to => 'dashboards#index', :as => :user_root
  
  # Project dashboard
  
  match 'dashboard', :to => 'dashboards#index'
  
  # Resource routes
  resources :accounts
  resources :projects
  resources :issues
  resources :uploads
  resources :clients
  resources :tasks
  resources :invoices
  
  match 'uploads/:user_id/share/:id', :to => 'uploads#share' 
  match 'invoices/view/:id', :to => 'invoices#view' 
  
  # API 
  
  namespace :api_v1 do
    scope ':key' do
      resources :projects
    end
  end
     
  # Default route
  
  root :to => redirect("/users/login")

end

app/models/issue.rb
class Issue
  
  include Core::Mongoid::Document
  
  ## fields ##
  
  field :title, :type => String
  field :description, :type => String
  field :status, :type => String
  field :project_title, :type => String
  field :raised_by, :type => String
    
  ## constants ##
  
  STATUSES = %w(open closed in-progress)
  
  ## validation ##
  
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :project_title
  
  ## associations ##
  
  embedded_in :user, :inverse_of => :issues
    
  ## scopes ##
  
  scope :recent, order_by(:created_at => :desc).limit(100)
  
  named_scope :open, :where => { :status => "open" }
  named_scope :closed, :where => { :status => "closed" }
  
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  
  respond_to :html
  
  before_filter :find_issue, :only => [:edit, :update, :destroy]

  def index
    @issues = @user.issues.page(params[:page]) 
    respond_with @issues
  end

  def show
    @issue = @user.issues.find(params[:id])
    respond_with @issue
  end

  def new
    @issue = @user.issues.new
    respond_with @issue
  end

  def edit
  end

  def create
    @issue = @user.issues.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
      else
        format.html { render action: "edit" } 
      end
    end
  end

  def destroy
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
    end
  end
  
  private
  
  def find_issue
    @issue = @user.issues.find(params[:id])
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.haml
= form_for @issue do |f|
  -if @issue.errors.any?
    #error_explanation
      %h2= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"
      %ul
        - @issue.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label "Project"
    = f.select :project_title, current_user.projects.collect{ |project| [project.title, project.title] }

  .field
    = f.label :description
    = f.text_field :description

  .field
    = f.hidden_field :raised_by, :value => current_user.name
  
  .actions
    = f.submit 'Save'

app/views/issues/edit.html.haml
%h1 Editing issue

= render 'form'

= link_to 'Show', @issue
\|
= link_to 'Back', issues_path

app/views/issues/index.html.haml
%h1 Listing issues

%p= paginate @issues

-if current_user.issues.present?

  %table
    %tr
      %th Title
      %th Project
      %th Description
      %th
      %th
      %th

    - @issues.each do |issue|
      %tr
        %td= issue.title
        %td= issue.project_title
        %td= issue.description
        %td= link_to 'Show', issue
        %td= link_to 'Edit', edit_issue_path(issue)
        %td= link_to 'Destroy', issue, :confirm => 'Are you sure?', :method => :delete

- else 
  
  %h3 Horray! No issues on any of your projects. You totally rock!

%br

= link_to 'New Issue', new_issue_path, :class => 'button'

app/views/issues/new.html.haml
%h1 New issue

- if current_user.projects.present?
  = render 'form'
- else
  %p You don't have any projects to assign issues to. Add a project in order to create new issues.

= link_to 'Back', issues_path

app/views/issues/show.html.haml
%h2= @issue.project_title

%h3= @issue.title

%p== Raised by: #{@issue.raised_by}
%p== Issue: #{@issue.description}

= link_to 'Back', issues_path