config/routes.rb
Baseapp::Application.routes.draw do

  # The front end site
  
  get "pages/index"
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'password', :confirmation => 'confirmation' }
  
  # When we log in a user through Devise, redirect them to the dashboard
  
  match '/user', :to => 'dashboards#index', :as => :user_root
  
  # Project dashboard
  
  match 'dashboard', :to => 'dashboards#index'
  
  # Resource routes
  resources :accounts
  resources :projects
  resources :issues
  resources :uploads
  resources :clients
  resources :tasks
  resources :invoices
  
  match 'uploads/:user_id/share/:id', :to => 'uploads#share' 
  match 'invoices/view/:id', :to => 'invoices#view' 
  
  # API 
  
  namespace :api_v1 do
    scope ':key' do
      resources :projects
    end
  end
     
  # Default route
  
  root :to => redirect("/users/login")

end

app/models/client.rb
class Client
  
  include Core::Mongoid::Document
  
  EMAIL_REGEX = /^[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  
  ## fields ##
  
  field :first_name, :type => String
  field :last_name, :type => String
  field :email, :type => String
  field :telephone, :type => String
  
  ## Validation ##
  
  validates_presence_of :first_name, :last_name
  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGEX }
  
  ## ##
  
  embedded_in :user, :inverse_of => :clients

  ## Methods ##
  
  # Returns a users full name
  #
  # @param 
  # @return
  
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
  # I find name quicker to remember
  
  alias_method :name, :full_name
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  respond_to :html
  
  before_filter :find_client, :only => [:show, :edit, :update, :destroy]
  
  def index
    @clients = @user.clients.page(params[:page]) 
    respond_with @clients
  end

  def show
    respond_with @client
  end

  def new
    @client = @user.clients.new
    respond_with @client
  end

  def edit
  end

  def create
    @client = @user.clients.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
    end
  end
  
  private 
  
  def find_client
    @client = @user.clients.find(params[:id])
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
  
  # 
  #
  # @param 
  # @return
  
  def find_client
    if @project.client_id.present?
      current_user.clients.find(@project.client_id).name
    else
      "N/A"
    end
  end
end

app/views/clients/_form.html.haml
= form_for @client do |f|
  -if @client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :telephone
    = f.text_field :telephone
  .actions
    = f.submit 'Save'

app/views/clients/edit.html.haml
%h1 Editing client

= render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/index.html.haml
%h1 Listing clients

%p= paginate @clients

- if @clients.blank?
  %p You don't have any clients yet.
- else
  %table
    %tr
      %th First name
      %th Last name
      %th Email
      %th Telephone
      %th
      %th

    - @clients.each do |client|
      %tr
        %td= client.first_name
        %td= client.last_name
        %td= client.email
        %td= client.telephone
        %td= link_to 'Edit', edit_client_path(client)
        %td= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete

  %br

= link_to 'New Client', new_client_path, :class => 'button'

app/views/clients/new.html.haml
%h1 New client

= render 'form'

app/views/clients/show.html.haml
%h1= @client.name

= avatar_url(@client)

%p== Email: #{@client.email}
%p== Phone: #{@client.telephone}

= link_to 'Edit', edit_client_path(@client)
\|
= link_to 'Back', clients_path