config/routes.rb
Baseapp::Application.routes.draw do

  # The front end site
  
  get "pages/index"
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'password', :confirmation => 'confirmation' }
  
  # When we log in a user through Devise, redirect them to the dashboard
  
  match '/user', :to => 'dashboards#index', :as => :user_root
  
  # Project dashboard
  
  match 'dashboard', :to => 'dashboards#index'
  
  # Resource routes
  resources :accounts
  resources :projects
  resources :issues
  resources :uploads
  resources :clients
  resources :tasks
  resources :invoices
  
  match 'uploads/:user_id/share/:id', :to => 'uploads#share' 
  match 'invoices/view/:id', :to => 'invoices#view' 
  
  # API 
  
  namespace :api_v1 do
    scope ':key' do
      resources :projects
    end
  end
     
  # Default route
  
  root :to => redirect("/users/login")

end

app/models/upload.rb
class Upload
  
  include Core::Mongoid::Document
  include Mongoid::Paperclip
  
  CATEGORY = %w(document design contract file).map {|type| type.camelize}.sort
  
  # This could be extracted into a more elegant set of config options.
  
  if Rails.env.production?
    has_mongoid_attached_file :file,
      :storage => :s3,
        :s3_credentials => {
          :access_key_id => ENV['S3_KEY'],
          :secret_access_key => ENV['S3_SECRET']
        },
        :bucket => ENV['S3_BUCKET'],
        :path => ":attachment/:id/:filename"
  else
    has_mongoid_attached_file :file 
  end
    
  ## Validation ##
  
  validates_presence_of :title
  
  validates_attachment_presence :file
  
  ## associations ##
  
  embedded_in :user, :inverse_of => :uploads
  
  ## fields ##
  
  field :title, :type => String
  field :category, :type => String
  field :is_public, :type => Boolean, :default => :false
  
  ## methods ##
  
  # Returns true if a file upload is an image
  #
  # @param 
  # @return [Boolean]

  def image?
    self.file_content_type == 'image/png' || self.file_content_type == 'image/jpeg'
  end
    
  ## methods ##
  
  # Returns the Amazon S3 URL for an upload
  #
  # @param 
  # @return [String] the url to the file upload on Amazon S3
  
  def s3_url
    "https://s3.amazonaws.com/#{ENV['S3_BUCKET']}"
  end
  
  # Returns true if an upload is to be shared 
  #
  # @param 
  # @return [Boolean]

  def is_public?
    self.is_public
  end
  
  # Returns the full path to a download so that it can be shared
  #
  # @param 
  # @return [String]

  def path
    self.file.to_s
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  respond_to :html
  
  skip_before_filter :authenticate_user!, :only => [:share]
  
  before_filter :find_upload, :only => [:show, :edit, :update, :destroy]
  
  def index
    @uploads = @user.uploads.page(params[:page]) 

    respond_to do |format|
      format.html 
    end
  end

  def show
    @upload = @user.uploads.find(params[:id])
    respond_with @upload
  end

  def new
    @upload = @user.uploads.new
    respond_with @upload
  end

  def edit
  end

  def create
    @upload = @user.uploads.new(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
    end
  end
  
  # Share an upload with an external user

  def share
    @user = User.find(params[:user_id])
    @upload = @user.uploads.find(params[:id])
    render :layout => 'share'
  end
  
  private 
  
  def find_upload
    @upload = @user.uploads.find(params[:id])
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.haml
= form_for @upload do |f|
  -if @upload.errors.any?
    #error_explanation
      %h2= "#{pluralize(@upload.errors.count, "error")} prohibited this upload from being saved:"
      %ul
        - @upload.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label :category
    = f.select :category, Upload::CATEGORY

  .field
    = f.label "Make_public"
    = f.check_box :is_public

  .field
    = f.label :file
    = f.file_field :file
	
  .actions
    = f.submit 'Save'

app/views/uploads/edit.html.haml
%h1 Editing upload

= render 'form'

= link_to 'Show', @upload
\|
= link_to 'Back', uploads_path

app/views/uploads/index.html.haml
%h1 Uploads
%p.description Uploads are a place to store your important documents like contracts and client proposals. Uploads that you make public can be shared directly with your clients.

- if @uploads.blank?
  %p You haven't uploaded any files yet.
-else
  %table
    %tr
      %th Title
      %th Category
      %th
      %th
      %th

    - @uploads.each do |upload|
      %tr
        %td= upload.title
        %td= upload.category
        %td= link_to 'Show', upload
        %td= link_to 'Edit', edit_upload_path(upload)
        %td= link_to 'Destroy', upload_path(upload), :confirm => 'Are you sure?', :method => :delete

  %br

= link_to 'New Upload', new_upload_path, :class => 'button'

app/views/uploads/new.html.haml
%h1 New upload

- unless current_user.upload_limit_reached?
  = render 'form'
- else
  %p Sorry but you've reached your account upload limit. Why not upgrade for more space?

= link_to 'Back', uploads_path

app/views/uploads/share.html.haml
%h1.center= @upload.title
%p.center== #{@user.name} wants to share a file with you. You are free to download this file.

-if @upload.image?
  %img{:src => @upload.file, :alt => @upload.title}
- else
  %br
  =link_to 'Download file', @upload.path

app/views/uploads/show.html.haml
%h2= @upload.title
%p= @upload.category

%p=link_to 'Download', @upload.file.to_s

- if @upload.is_public?
  %p Copy the URL below to share your file with others.
  %pre
    %code
      ="#{root_url}uploads/#{@user.id}/share/#{@upload.id}"

- if @upload.image?
  %img{:src => @upload.file, :alt => @upload.title}

%br 

= link_to 'Edit', edit_upload_path(@upload)
\|
= link_to 'Back', uploads_path