config/routes.rb
Baseapp::Application.routes.draw do

  # The front end site
  
  get "pages/index"
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'password', :confirmation => 'confirmation' }
  
  # When we log in a user through Devise, redirect them to the dashboard
  
  match '/user', :to => 'dashboards#index', :as => :user_root
  
  # Project dashboard
  
  match 'dashboard', :to => 'dashboards#index'
  
  # Resource routes
  resources :accounts
  resources :projects
  resources :issues
  resources :uploads
  resources :clients
  resources :tasks
  resources :invoices
  
  match 'uploads/:user_id/share/:id', :to => 'uploads#share' 
  match 'invoices/view/:id', :to => 'invoices#view' 
  
  # API 
  
  namespace :api_v1 do
    scope ':key' do
      resources :projects
    end
  end
     
  # Default route
  
  root :to => redirect("/users/login")

end

app/views/layouts/application.html.haml
!!!5
%html{:class => 'no-js', :lang => 'en'}
  %head
    %meta{:charset => 'utf-8'}
    %title FunnelHQ | Business Management for Freelancers
    %script{:src =>'http://html5shim.googlecode.com/svn/trunk/html5.js'}
    
    %link{:href =>'http://fonts.googleapis.com/css?family=Lato:400,700', :rel =>'stylesheet', :type =>'text/css'}
    %link{:href =>'http://fonts.googleapis.com/css?family=PT+Serif:400,700', :rel =>'stylesheet', :type =>'text/css'}

    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'	
    = csrf_meta_tags

  #nav
    = render 'shared/nav'

  %body
    #sidebar
      %ul
        %li{:class => "#{nav_link_class('dashboards')}"}
          =link_to 'Dashboard', dashboard_path
          %span Your dashboard

        %li{:class => "#{nav_link_class('projects')}"}
          =link_to 'Projects', projects_path
          %span Manage projects

        %li{:class => "#{nav_link_class('tasks')}"}
          = link_to 'Tasks', tasks_path
          %span Manage tasks
 
        %li{:class => "#{nav_link_class('clients')}"}
          = link_to 'Clients', clients_path
          %span Manage clients

        %li{:class => "#{nav_link_class('invoices')}"}
          = link_to 'Invoices', invoices_path
          %span Manage invoices

        %li{:class => "#{nav_link_class('issues')}"}
          = link_to 'Issues', issues_path
          %span Assign issues to projects

        %li{:class => "#{nav_link_class('uploads')}"}
          = link_to 'Uploads', uploads_path
          %span Upload files

    #main
      - flash.each do |key, msg|
        = content_tag :div, msg, :class => "#{key}" 

      =yield

app/views/layouts/devise.html.haml
!!!5
%html{:class => "no-js", :lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title Freelance Deck
    %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body#devise

    =yield

app/views/layouts/invoice.html.haml
!!!5
%html{:class => "no-js", :lang => "en", :id => "invoice_view"}
  %head
    %meta{:charset => "utf-8"}
    %title Funnel HQ
    %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    = stylesheet_link_tag    "application"

    = csrf_meta_tags
  
  %body

    .container#share
 
      = yield

app/views/layouts/login.html.haml
!!!5
%html{:class => "no-js", :lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title Funnel HQ | Login
    %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body#devise

    =yield

app/views/layouts/pages.html.haml
!!!5
%html{:class => "no-js", :lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title Funnel HQ
    %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    = stylesheet_link_tag    "application"

    = csrf_meta_tags
  
  %body#pages
    

app/views/layouts/share.html.haml
!!!5
%html{:class => "no-js", :lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title Funnel HQ
    %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    = stylesheet_link_tag    "application"

    = csrf_meta_tags
  
  %body#pages

    .container#share
 
      = yield